describe('Orange HRM Tests', () => {
  it('1 - Login - Success', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get("[name='username']").type('Admin')
    cy.get("[name='password']").type('admin123')
    cy.get("[type='submit']").click()
    cy.location('pathname').should('equal', '/web/index.php/dashboard/index')
    cy.get('.oxd-topbar-header-breadcrumb-module').contains('Dashboard')
  })
  it('2 - Login - Fail - Username', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get("[name='username']").type('teste')
    cy.get("[name='password']").type('admin123')
    cy.get("[type='submit']").click()
    cy.get("[role='alert']")
  })
  it('3 - Login - Fail - Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get("[name='username']").type('Admin')
    cy.get("[name='password']").type('teste')
    cy.get("[type='submit']").click()
    cy.get("[role='alert']")
  })
  it('4 - Login - Fail - No Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get("[name='username']").type('Admin')    
    cy.get("[type='submit']").click()
    cy.get('.oxd-input-field-error-message')
  })
  it('5 - Login - Fail - No Username', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login') .wait(1000)   
    cy.get("[name='password']").type('admin123')
    cy.get("[type='submit']").click()
    cy.get('.oxd-input-group__message')
  })
  it('6 - Login - Fail - No Usarname/Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get("[type='submit']").click()
    cy.get('.oxd-input-group__message')
  })
  it('7 - Login - Fail - Forgot your Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get('.orangehrm-login-forgot-header').click()
    cy.get('.oxd-text--h6')    
    cy.get("[name='username']").type('Admin')
    cy.get("[type='submit']").click() 
    cy.get('.orangehrm-forgot-password-title')
  })
  it('8 - Login - Fail - Forgot your Password - No Usarname', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get('.orangehrm-login-forgot-header').click()
    cy.get('.oxd-text--h6')        
    cy.get("[type='submit']").click() 
    cy.get('.oxd-text--span')
  })
  it('9 - Login - Fail - Forgot your Password - Return Home', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login').wait(1000)
    cy.get('.orangehrm-login-forgot-header').click()
    cy.get('.oxd-text--h6')        
    cy.get("[type='submit']").click() 
    cy.get('.oxd-text--span')
    cy.get("[type='button']").click()
    cy.get('.orangehrm-login-forgot-header')
  })
})